import type {Locale} from './i18n';

const en={
 choose:'Who are you buying for?',dealer:'Auto parts business',garage:'Repair workshop',owner:'Private car owner',dealerHint:'Parts shops, distributors and dealers',garageHint:'Garages and vehicle service centres',ownerHint:'Parts for your own vehicle',
 intro:'Choose your customer type so our team can prepare the right quotation.',welcome:'Welcome to NEVERSTOP. For an accurate quotation, please tell us your region, vehicle model, year and the product you need.',
 details:'Your enquiry',optional:'You can fill in these details now, or provide them in the chat.',region:'Region / city',vehicle:'Vehicle model',year:'Production year',product:'Product needed',name:'Name / company (optional)',phone:'Phone (optional)',quantity:'Quantity (optional)',
 recordNote:'Your selection and any details you provide will be shared with the NEVERSTOP sales team.',change:'Change customer type',continue:'Prepare enquiry',saving:'Saving…',saved:'Your enquiry is saved.',error:'We could not save your enquiry. Please try again.',rateLimit:'Too many attempts. Please try again later.',
 reference:'Enquiry reference',close:'Close',copy:'Copy enquiry',copied:'Copied. Paste it into Zalo and send.',copyFailed:'Select and copy the message below, then paste it into Zalo.',zaloHint:'Zalo does not prefill this message. Copy it, paste it into the chat and send it.',sendHint:'Review the prepared message and press Send in your messaging or email app.',open:'Open',email:'Email',chat:'Enquiry message',pending:'Not provided yet',
 customerType:'Customer type',channel:'Contact channel',partNumber:'NEVERSTOP Part Number',oem:'Reference OEM',chassis:'Chassis / vehicle code',source:'Source page',hello:'Hello NEVERSTOP, I would like a quotation.',
};
type Copy=typeof en;
const copy:Record<Locale,Copy>={
 en,
 zh:{choose:'请选择客户类型',dealer:'汽配商家',garage:'汽修店',owner:'个人车主',dealerHint:'汽配店、经销商、代理商',garageHint:'维修厂、汽修店、保养服务',ownerHint:'为自己的车辆选购配件',intro:'请选择您的客户类型，方便我们提供合适的报价。',welcome:'欢迎咨询 NEVERSTOP！为了准确报价，请提供您所在区域、车型、年份，以及需要的产品。',details:'您的咨询信息',optional:'可以先填写，也可以进入聊天后补充。',region:'所在区域 / 城市',vehicle:'车型',year:'生产年份',product:'需要什么产品',name:'姓名 / 公司（选填）',phone:'联系电话（选填）',quantity:'数量（选填）',recordNote:'您的客户类型及填写的信息将提供给 NEVERSTOP 销售团队。',change:'重新选择客户类型',continue:'准备咨询',saving:'正在保存…',saved:'咨询信息已保存。',error:'咨询信息暂时无法保存，请重试。',rateLimit:'操作过于频繁，请稍后重试。',reference:'咨询编号',close:'关闭',copy:'复制咨询内容',copied:'已复制，请粘贴到 Zalo 并发送。',copyFailed:'请选择并复制下方内容，然后粘贴到 Zalo。',zaloHint:'Zalo 不会自动填入这段消息，请复制后粘贴到聊天框并发送。',sendHint:'请在聊天或邮件应用中确认内容，再点击发送。',open:'打开',email:'邮箱',chat:'咨询消息',pending:'待补充',customerType:'客户类型',channel:'联系渠道',partNumber:'NEVERSTOP 产品编号',oem:'OEM 参考号',chassis:'底盘 / 车型代号',source:'来源页面',hello:'您好 NEVERSTOP，我想咨询产品报价。'},
 vi:{choose:'Bạn thuộc nhóm khách hàng nào?',dealer:'Cửa hàng phụ tùng',garage:'Gara sửa chữa',owner:'Chủ xe cá nhân',dealerHint:'Cửa hàng, nhà phân phối và đại lý phụ tùng',garageHint:'Gara, xưởng sửa chữa và bảo dưỡng',ownerHint:'Mua phụ tùng cho xe của mình',intro:'Vui lòng chọn nhóm khách hàng để chúng tôi tư vấn báo giá phù hợp.',welcome:'Chào mừng anh/chị đến với NEVERSTOP! Để báo giá chính xác, vui lòng cung cấp khu vực, dòng xe, năm sản xuất và sản phẩm cần mua.',details:'Thông tin tư vấn',optional:'Anh/chị có thể điền ngay hoặc bổ sung trong cuộc trò chuyện.',region:'Khu vực / tỉnh, thành phố',vehicle:'Dòng xe',year:'Năm sản xuất',product:'Sản phẩm cần mua',name:'Tên / công ty (không bắt buộc)',phone:'Số điện thoại (không bắt buộc)',quantity:'Số lượng (không bắt buộc)',recordNote:'Nhóm khách hàng và thông tin anh/chị cung cấp được chia sẻ với đội ngũ tư vấn NEVERSTOP.',change:'Chọn lại nhóm khách hàng',continue:'Chuẩn bị nội dung tư vấn',saving:'Đang lưu…',saved:'Đã lưu thông tin tư vấn.',error:'Chưa lưu được thông tin. Vui lòng thử lại.',rateLimit:'Quá nhiều thao tác. Vui lòng thử lại sau.',reference:'Mã tư vấn',close:'Đóng',copy:'Sao chép nội dung',copied:'Đã sao chép. Vui lòng dán vào Zalo và gửi.',copyFailed:'Vui lòng chọn, sao chép nội dung bên dưới rồi dán vào Zalo.',zaloHint:'Zalo không tự điền nội dung này. Vui lòng sao chép, dán vào cuộc trò chuyện và gửi.',sendHint:'Vui lòng kiểm tra nội dung và bấm Gửi trong ứng dụng nhắn tin hoặc email.',open:'Mở',email:'Email',chat:'Nội dung tư vấn',pending:'Chưa cung cấp',customerType:'Nhóm khách hàng',channel:'Kênh liên hệ',partNumber:'Mã sản phẩm NEVERSTOP',oem:'Mã OEM tham khảo',chassis:'Mã khung / mã xe',source:'Trang nguồn',hello:'Xin chào NEVERSTOP, tôi muốn được tư vấn báo giá.'},
 ar:{choose:'ما نوع العميل؟',dealer:'متجر قطع غيار',garage:'ورشة إصلاح سيارات',owner:'مالك سيارة فردي',dealerHint:'متاجر وموزعو قطع الغيار',garageHint:'ورش إصلاح وصيانة السيارات',ownerHint:'قطع غيار لسيارتك الخاصة',intro:'اختر نوع العميل لنقدم عرض السعر المناسب.',welcome:'أهلاً بك في NEVERSTOP. للحصول على عرض سعر دقيق، يرجى تزويدنا بالمنطقة وطراز السيارة وسنة الصنع والمنتج المطلوب.',details:'تفاصيل الاستفسار',optional:'يمكنك إدخال التفاصيل الآن أو تقديمها في المحادثة.',region:'المنطقة / المدينة',vehicle:'طراز السيارة',year:'سنة الصنع',product:'المنتج المطلوب',name:'الاسم / الشركة (اختياري)',phone:'رقم الهاتف (اختياري)',quantity:'الكمية (اختياري)',recordNote:'ستتم مشاركة اختيارك ومعلوماتك مع فريق مبيعات NEVERSTOP.',change:'تغيير نوع العميل',continue:'تجهيز الاستفسار',saving:'جارٍ الحفظ…',saved:'تم حفظ الاستفسار.',error:'تعذر الحفظ. يرجى المحاولة مرة أخرى.',rateLimit:'محاولات كثيرة. حاول لاحقاً.',reference:'رقم الاستفسار',close:'إغلاق',copy:'نسخ الاستفسار',copied:'تم النسخ. الصق الرسالة في Zalo وأرسلها.',copyFailed:'حدد النص أدناه وانسخه ثم الصقه في Zalo.',zaloHint:'لا يملأ Zalo هذه الرسالة تلقائياً. انسخها والصقها في المحادثة وأرسلها.',sendHint:'راجع الرسالة واضغط إرسال في تطبيق المحادثة أو البريد.',open:'فتح',email:'البريد الإلكتروني',chat:'رسالة الاستفسار',pending:'لم يتم تقديمه بعد',customerType:'نوع العميل',channel:'قناة التواصل',partNumber:'رقم قطعة NEVERSTOP',oem:'مرجع OEM',chassis:'رمز الهيكل / السيارة',source:'صفحة المصدر',hello:'مرحباً NEVERSTOP، أود الحصول على عرض سعر.'},
 es:{choose:'¿Qué tipo de cliente eres?',dealer:'Comercio de recambios',garage:'Taller de reparación',owner:'Propietario particular',dealerHint:'Tiendas, distribuidores y concesionarios',garageHint:'Talleres y centros de mantenimiento',ownerHint:'Piezas para tu propio vehículo',intro:'Elige tu tipo de cliente para recibir la cotización adecuada.',welcome:'Bienvenido a NEVERSTOP. Para una cotización precisa, indica tu región, modelo del vehículo, año y producto que necesitas.',details:'Tu consulta',optional:'Puedes completar los datos ahora o en el chat.',region:'Región / ciudad',vehicle:'Modelo del vehículo',year:'Año de fabricación',product:'Producto necesario',name:'Nombre / empresa (opcional)',phone:'Teléfono (opcional)',quantity:'Cantidad (opcional)',recordNote:'Tu selección y los datos que facilites se compartirán con el equipo de ventas de NEVERSTOP.',change:'Cambiar tipo de cliente',continue:'Preparar consulta',saving:'Guardando…',saved:'Consulta guardada.',error:'No se pudo guardar. Inténtalo de nuevo.',rateLimit:'Demasiados intentos. Inténtalo más tarde.',reference:'Referencia de consulta',close:'Cerrar',copy:'Copiar consulta',copied:'Copiado. Pégalo en Zalo y envíalo.',copyFailed:'Selecciona y copia el mensaje de abajo y pégalo en Zalo.',zaloHint:'Zalo no rellena este mensaje automáticamente. Cópialo, pégalo en el chat y envíalo.',sendHint:'Revisa el mensaje y pulsa Enviar en tu aplicación de chat o correo.',open:'Abrir',email:'Email',chat:'Mensaje de consulta',pending:'Por completar',customerType:'Tipo de cliente',channel:'Canal de contacto',partNumber:'Referencia NEVERSTOP',oem:'Referencia OEM',chassis:'Código de chasis / vehículo',source:'Página de origen',hello:'Hola NEVERSTOP, quisiera solicitar una cotización.'},
 pt:{choose:'Que tipo de cliente é?',dealer:'Comércio de autopeças',garage:'Oficina de reparação',owner:'Proprietário particular',dealerHint:'Lojas, distribuidores e revendedores',garageHint:'Oficinas e centros de manutenção',ownerHint:'Peças para o seu próprio veículo',intro:'Escolha o tipo de cliente para receber o orçamento adequado.',welcome:'Bem-vindo à NEVERSTOP. Para um orçamento preciso, indique a região, o modelo do veículo, o ano e o produto pretendido.',details:'A sua consulta',optional:'Pode preencher agora ou fornecer os dados na conversa.',region:'Região / cidade',vehicle:'Modelo do veículo',year:'Ano de fabrico',product:'Produto pretendido',name:'Nome / empresa (opcional)',phone:'Telefone (opcional)',quantity:'Quantidade (opcional)',recordNote:'A sua seleção e os dados fornecidos serão partilhados com a equipa de vendas NEVERSTOP.',change:'Alterar tipo de cliente',continue:'Preparar consulta',saving:'A guardar…',saved:'Consulta guardada.',error:'Não foi possível guardar. Tente novamente.',rateLimit:'Demasiadas tentativas. Tente mais tarde.',reference:'Referência da consulta',close:'Fechar',copy:'Copiar consulta',copied:'Copiado. Cole no Zalo e envie.',copyFailed:'Selecione e copie a mensagem abaixo e cole no Zalo.',zaloHint:'O Zalo não preenche esta mensagem automaticamente. Copie, cole na conversa e envie.',sendHint:'Verifique a mensagem e prima Enviar na aplicação de conversa ou email.',open:'Abrir',email:'Email',chat:'Mensagem de consulta',pending:'Por preencher',customerType:'Tipo de cliente',channel:'Canal de contacto',partNumber:'Referência NEVERSTOP',oem:'Referência OEM',chassis:'Código de chassis / veículo',source:'Página de origem',hello:'Olá NEVERSTOP, gostaria de solicitar um orçamento.'},
};
export function contactIntakeCopy(locale:Locale){return copy[locale];}
