import type {Locale} from './i18n';
export const languageNames={vi:'Tiếng Việt',en:'English',zh:'中文',ar:'العربية',es:'Español',pt:'Português'};
export const languageCodes={vi:'VI',en:'EN',zh:'中文',ar:'العربية',es:'ES',pt:'PT'};
export const headerCopy={
 zh:{home:'首页',products:'产品',vehicle:'按车型查找',contact:'联系我们',orders:'我的订单',language:'语言',quote:'询价',menu:'菜单',skip:'跳至正文',social:'社媒快捷入口',pending:'链接待确认',videoPending:'Zalo Video 链接待确认',empty:'通过专属链接查看订单',orderHint:'请使用 NEVERSTOP 发给您的专属订单链接查看订单。此页面暂未提供订单汇总。',brandLine:'FACTORY-DIRECT · CHINA | VIETNAM'},
 vi:{home:'Trang chủ',products:'Sản phẩm',vehicle:'Tìm theo xe',contact:'Liên hệ',orders:'Đơn hàng của tôi',language:'Ngôn ngữ',quote:'Yêu cầu báo giá',menu:'Menu',skip:'Đến nội dung',social:'Mạng xã hội',pending:'Đang xác nhận liên kết',videoPending:'Đang cập nhật biểu tượng và liên kết Zalo Video',empty:'Xem đơn hàng qua liên kết riêng',orderHint:'Vui lòng dùng liên kết đơn hàng riêng do NEVERSTOP gửi. Trang này chưa cung cấp danh sách đơn hàng.',brandLine:'FACTORY-DIRECT · CHINA | VIETNAM'},
 en:{home:'Home',products:'Products',vehicle:'Find by vehicle',contact:'Contact',orders:'My Orders',language:'Language',quote:'Request Quote',menu:'Menu',skip:'Skip to content',social:'Social links',pending:'Link not yet confirmed',videoPending:'Zalo Video link pending',empty:'View your order with its private link',orderHint:'Use the private order link sent by NEVERSTOP. An order list is not available on this page yet.',brandLine:'FACTORY-DIRECT · CHINA | VIETNAM'},
 ar:{home:'الرئيسية',products:'المنتجات',vehicle:'البحث حسب السيارة',contact:'اتصل بنا',orders:'طلباتي',language:'اللغة',quote:'طلب عرض سعر',menu:'القائمة',skip:'انتقل إلى المحتوى',social:'وسائل التواصل',pending:'الرابط غير مؤكد بعد',videoPending:'شعار ورابط Zalo Video قيد الإعداد',empty:'اعرض طلبك عبر الرابط الخاص',orderHint:'استخدم رابط الطلب الخاص الذي أرسلته NEVERSTOP. قائمة الطلبات غير متاحة هنا بعد.',brandLine:'FACTORY-DIRECT · CHINA | VIETNAM'},
 es:{home:'Inicio',products:'Productos',vehicle:'Buscar por vehículo',contact:'Contacto',orders:'Mis pedidos',language:'Idioma',quote:'Solicitar cotización',menu:'Menú',skip:'Saltar al contenido',social:'Redes sociales',pending:'Enlace por confirmar',videoPending:'Icono y enlace de Zalo Video pendientes',empty:'Consulta tu pedido con su enlace privado',orderHint:'Utiliza el enlace privado enviado por NEVERSTOP. Esta página aún no ofrece una lista de pedidos.',brandLine:'FACTORY-DIRECT · CHINA | VIETNAM'},
 pt:{home:'Início',products:'Produtos',vehicle:'Buscar por veículo',contact:'Contato',orders:'Meus pedidos',language:'Idioma',quote:'Solicitar orçamento',menu:'Menu',skip:'Ir para o conteúdo',social:'Redes sociais',pending:'Link a confirmar',videoPending:'Ícone e link do Zalo Video pendentes',empty:'Veja seu pedido pelo link privado',orderHint:'Use o link privado enviado pela NEVERSTOP. Esta página ainda não apresenta uma lista de pedidos.',brandLine:'FACTORY-DIRECT · CHINA | VIETNAM'}
} satisfies Record<Locale,Record<string,string>>;
