import type {Locale} from './i18n';
const en={
 direct:'Factory-direct',line1:'Every journey,',highlight:'more stable,',line2:'more reassuring.',intro:'High-quality chassis parts · Multiple vehicle applications · Continuously expanding',
 benefits:['Standard specifications','Long-lasting stability','After-sales support','Hanoi availability'],benefitNotes:['Verified parameters','Comfortable handling','Professional support','Confirm with our team'],
 categories:'Product Categories',moreProducts:'View more products',
 factoryTitle:'Factory-direct · Quality you can see',factoryBody:'From production and testing to packaging and delivery, every step matters. Dependable shock absorbers for our customers.',factoryCta:'See the factory',
 stages:['Manufacturing','Quality testing','Warehouse stock','Packing & shipping'],stageNotes:['Rigorous processes, consistent quality','Shock absorber performance testing','Prepared stock and dispatch','Secure packaging, reliable delivery'],
 storeTitle:'Visit us in Hanoi',storeBody:'Hanoi store · Warehouse supply · Delivery across Vietnam',storeContact:'Visit our team or contact us through Zalo / WhatsApp.',address:'Store address',hours:'Opening hours',confirmHours:'Contact us to confirm',qr:'Scan to contact',zalo:'Zalo inquiry',email:'Email',
 illustration:'Temporary reference imagery',visualNote:'Images are temporary illustrations. Confirm vehicle fitment and availability through the catalog and our team.',previous:'Previous batch',next:'Next batch',
};
type Copy=typeof en;
const copy:Record<Locale,Copy>={
 en,
 zh:{...en,direct:'工厂直供',line1:'让每一次出行',highlight:'更平稳，',line2:'更安心',intro:'高品质汽车底盘零部件 · 覆盖多车型 · 持续扩展中',benefits:['标准参数','耐久稳定','售后保障','河内现货'],benefitNotes:['严格制造','舒适驾驶','放心使用','全国发货'],categories:'产品类别',moreProducts:'查看更多产品',factoryTitle:'工厂直供 · 品质看得见',factoryBody:'从生产、检测到包装发货，严格把控每一个环节。为客户提供稳定、可靠的减震器产品。',factoryCta:'观看工厂实拍',stages:['生产制造','质量检测','仓储备货','包装出货'],stageNotes:['严谨工艺，稳定品质','多项性能测试','库存充足，快速发货','安全包装，送达客户'],storeTitle:'欢迎来到河内门店',storeBody:'河内门店 · 仓库现货 · 越南全国可发货',storeContact:'欢迎到店咨询或通过 Zalo / WhatsApp 联系我们。',address:'门店地址',hours:'营业时间',confirmHours:'联系门店确认',qr:'扫码联系',zalo:'Zalo 咨询',email:'联系邮箱',illustration:'临时参考图片',visualNote:'图片暂用参考素材，具体适配与现货请通过车型查询及人工确认。',previous:'上一批车型',next:'下一批车型'},
 vi:{...en,direct:'Trực tiếp từ nhà máy',line1:'Mỗi hành trình,',highlight:'vững vàng hơn,',line2:'an tâm hơn.',intro:'Phụ tùng gầm xe chất lượng cao · Phù hợp nhiều dòng xe · Không ngừng mở rộng',benefits:['Thông số tiêu chuẩn','Ổn định bền bỉ','Hỗ trợ sau bán hàng','Hàng tại Hà Nội'],benefitNotes:['Sản xuất nghiêm ngặt','Lái xe thoải mái','An tâm sử dụng','Giao hàng toàn quốc'],categories:'Danh mục sản phẩm',moreProducts:'Xem thêm sản phẩm',factoryTitle:'Trực tiếp từ nhà máy · Chất lượng rõ ràng',factoryBody:'Kiểm soát từng công đoạn từ sản xuất, kiểm tra đến đóng gói và giao hàng. Cung cấp giảm xóc ổn định và đáng tin cậy.',factoryCta:'Xem nhà máy',stages:['Sản xuất','Kiểm tra chất lượng','Kho hàng','Đóng gói & giao hàng'],stageNotes:['Quy trình chặt chẽ, chất lượng ổn định','Kiểm tra hiệu suất giảm xóc','Chuẩn bị hàng và giao hàng','Đóng gói an toàn, giao đến khách'],storeTitle:'Gặp chúng tôi tại Hà Nội',storeBody:'Cửa hàng Hà Nội · Cung ứng từ kho · Giao hàng toàn quốc',storeContact:'Đến cửa hàng hoặc liên hệ qua Zalo / WhatsApp.',address:'Địa chỉ cửa hàng',hours:'Giờ mở cửa',confirmHours:'Liên hệ để xác nhận',qr:'Quét để liên hệ',zalo:'Tư vấn Zalo',email:'Email liên hệ',illustration:'Hình tham khảo tạm thời',visualNote:'Hình ảnh minh họa tạm thời. Tra cứu và xác nhận độ phù hợp, tình trạng hàng với tư vấn viên.',previous:'Nhóm xe trước',next:'Nhóm xe tiếp theo'},
 ar:{...en,direct:'مباشرة من المصنع',line1:'في كل رحلة،',highlight:'ثبات أكبر،',line2:'واطمئنان أكثر.',intro:'قطع هيكل عالية الجودة · توافق مع سيارات متعددة · توسع مستمر',benefits:['مواصفات قياسية','ثبات ومتانة','دعم ما بعد البيع','التوفر في هانوي'],benefitNotes:['تصنيع دقيق','قيادة مريحة','دعم متخصص','تأكيد التوفر مع الفريق'],categories:'فئات المنتجات',moreProducts:'عرض المزيد من المنتجات',factoryTitle:'مباشرة من المصنع · جودة تراها',factoryBody:'نهتم بكل مرحلة من التصنيع والاختبار إلى التعبئة والتسليم لتوفير ممتصات صدمات موثوقة.',factoryCta:'شاهد المصنع',stages:['التصنيع','اختبار الجودة','المستودع','التعبئة والشحن'],stageNotes:['عمليات دقيقة وجودة ثابتة','اختبار أداء ممتص الصدمات','تجهيز الطلبات للإرسال','تغليف آمن وتسليم موثوق'],storeTitle:'زورونا في هانوي',storeBody:'متجر هانوي · توريد من المستودع · توصيل داخل فيتنام',storeContact:'زوروا فريقنا أو تواصلوا عبر Zalo / WhatsApp.',address:'عنوان المتجر',hours:'ساعات العمل',confirmHours:'تواصل لتأكيد المواعيد',qr:'امسح للتواصل',zalo:'استفسار Zalo',email:'البريد الإلكتروني',illustration:'صور مرجعية مؤقتة',visualNote:'الصور توضيحية مؤقتة. أكد التوافق والتوفر عبر الكتالوج وفريقنا.',previous:'المجموعة السابقة',next:'المجموعة التالية'},
 es:{...en,direct:'Directo de fábrica',line1:'En cada viaje,',highlight:'más estabilidad,',line2:'más tranquilidad.',intro:'Piezas de chasis de alta calidad · Múltiples vehículos · Expansión continua',benefits:['Especificaciones estándar','Estabilidad duradera','Soporte posventa','Disponibilidad en Hanói'],benefitNotes:['Fabricación rigurosa','Conducción cómoda','Soporte profesional','Confirmar con el equipo'],categories:'Categorías de productos',moreProducts:'Ver más productos',factoryTitle:'Directo de fábrica · Calidad visible',factoryBody:'Cuidamos cada etapa, desde la fabricación y las pruebas hasta el embalaje y la entrega. Amortiguadores fiables para nuestros clientes.',factoryCta:'Ver la fábrica',stages:['Fabricación','Pruebas de calidad','Almacén','Embalaje y envío'],stageNotes:['Procesos rigurosos, calidad constante','Pruebas de rendimiento','Preparación y envío de pedidos','Embalaje seguro, entrega fiable'],storeTitle:'Visítanos en Hanói',storeBody:'Tienda en Hanói · Suministro desde almacén · Envíos en Vietnam',storeContact:'Visítanos o contáctanos por Zalo / WhatsApp.',address:'Dirección',hours:'Horario',confirmHours:'Contactar para confirmar',qr:'Escanear para contactar',zalo:'Consulta por Zalo',email:'Correo electrónico',illustration:'Imágenes de referencia temporales',visualNote:'Imágenes ilustrativas temporales. Confirma compatibilidad y disponibilidad con el catálogo y nuestro equipo.',previous:'Grupo anterior',next:'Grupo siguiente'},
 pt:{...en,direct:'Direto da fábrica',line1:'Em cada viagem,',highlight:'mais estabilidade,',line2:'mais tranquilidade.',intro:'Peças de chassis de alta qualidade · Vários veículos · Expansão contínua',benefits:['Especificações padrão','Estabilidade duradoura','Suporte pós-venda','Disponibilidade em Hanói'],benefitNotes:['Fabricação rigorosa','Condução confortável','Suporte profissional','Confirme com a equipe'],categories:'Categorias de produtos',moreProducts:'Ver mais produtos',factoryTitle:'Direto da fábrica · Qualidade visível',factoryBody:'Cuidamos de cada etapa, da fabricação e dos testes à embalagem e entrega. Amortecedores confiáveis para os nossos clientes.',factoryCta:'Ver a fábrica',stages:['Fabricação','Testes de qualidade','Armazém','Embalagem e envio'],stageNotes:['Processos rigorosos, qualidade constante','Testes de desempenho','Preparação e expedição de pedidos','Embalagem segura, entrega confiável'],storeTitle:'Visite-nos em Hanói',storeBody:'Loja em Hanói · Fornecimento do armazém · Entrega no Vietnã',storeContact:'Visite nossa equipe ou entre em contato por Zalo / WhatsApp.',address:'Endereço',hours:'Horário',confirmHours:'Entre em contato para confirmar',qr:'Digitalize para entrar em contato',zalo:'Consulta pelo Zalo',email:'E-mail',illustration:'Imagens de referência temporárias',visualNote:'Imagens ilustrativas temporárias. Confirme compatibilidade e disponibilidade no catálogo e com a nossa equipe.',previous:'Grupo anterior',next:'Próximo grupo'},
};
export function homeReferenceCopy(locale:Locale){return copy[locale];}
