import type {Locale} from './i18n';
const en={
 heroDirect:'Factory-direct',heroProduct:'Automotive Shock Absorbers',heroCertification:'Quality certified',heroSince:'Since',heroYear:'1983',
 title:'Product Center',intro:'High-quality chassis parts for multiple vehicle applications, continuously expanding.',introSecondary:'Các sản phẩm gầm xe chất lượng cao cho nhiều dòng xe, liên tục mở rộng.',
 quality:'Reliable Quality',qualitySecondary:'Chất lượng bền bỉ',fitment:'Wide Fitment',fitmentSecondary:'Ứng dụng rộng rãi',expansion:'More Products Coming Soon',expansionSecondary:'Tiếp tục mở rộng sản phẩm',
 categoryTitles:['Shock Absorbers','Suspension Parts','Steering Parts','Brake Parts','Rubber Parts','Other Parts'],comingSoon:'coming soon',
 shockTitle:'Shock Absorbers',shockSubtitle:' / Giảm xóc ô tô',
 shockDescription:'NEVERSTOP shock absorbers are manufactured with high-quality materials and strict processes, providing stable handling, comfort, and durability for a wide range of vehicle models.',shockSecondary:'Giảm xóc NEVERSTOP được sản xuất với vật liệu chất lượng cao và quy trình nghiêm ngặt, mang lại sự ổn định, êm ái và bền bỉ cho nhiều dòng xe.',
 byVehicle:'Find by vehicle',byOem:'Find by OEM number',byPart:'Find by part number',brand:'Select brand',model:'Select model',year:'Select years',brandExample:'e.g. Toyota',modelExample:'e.g. Vios',yearExample:'e.g. 2014 – 2022',oem:'Reference OEM',part:'NEVERSTOP Part Number',oemExample:'Enter a reference OEM number',partExample:'Enter a NEVERSTOP part number',search:'Find products',
 popular:'Popular Vehicle Shock Absorbers',popularIntro:'Quality shock absorbers for popular vehicles in Vietnam and worldwide',moreVehicles:'View more vehicles',vehicleProduct:'Shock Absorber',
 moreCategories:'More Product Categories Coming Soon',moreIntro:'We are continuously expanding our product range, including suspension, steering, brake parts and more.',moreSecondary:'Chúng tôi đang tiếp tục mở rộng các sản phẩm gầm xe. Hãy đón chờ!',follow:'Follow us for the latest product updates',
};
type Copy=typeof en;
const copy:Record<Locale,Copy>={
 en,
 zh:{...en,heroDirect:'工厂直供',heroProduct:'汽车减震器',heroCertification:'质量认证',title:'产品中心',intro:'高品质汽车底盘零部件，覆盖多车型应用，持续扩展中。',introSecondary:en.intro,quality:'稳定耐用',qualitySecondary:en.quality,fitment:'适配广泛',fitmentSecondary:en.fitment,expansion:'持续扩展更多产品',expansionSecondary:en.expansion,categoryTitles:['减震器','悬挂系统','转向系统','制动系统','底盘橡胶件','其他产品'],shockTitle:'减震器',shockSubtitle:' / Shock Absorbers / Giảm xóc ô tô',shockDescription:'NEVERSTOP 减震器采用高品质材料与严格工艺制造，提供稳定的操控性、舒适性与耐用性，适用于多种车型。',shockSecondary:en.shockDescription,byVehicle:'按车型查找',byOem:'按OEM号查找',byPart:'按产品编号查找',brand:'选择品牌',model:'选择车型',year:'选择年份',brandExample:'例如：Toyota',modelExample:'例如：Vios',yearExample:'例如：2014 – 2022',oem:'OEM 参考号',part:'NEVERSTOP 产品编号',oemExample:'输入 OEM 参考号',partExample:'输入 NEVERSTOP 产品编号',search:'查找产品',popular:'热门车型减震器',popularIntro:'为越南及全球热门车型提供优质减震器产品',moreVehicles:'查看更多车型',vehicleProduct:'减震器 / Shock Absorber',moreCategories:'更多产品类别 敬请期待',moreIntro:en.moreIntro,moreSecondary:'我们正在持续扩展更多汽车底盘零部件产品，敬请期待。',follow:'关注我们，获取最新产品信息'},
 vi:{...en,heroDirect:'Trực tiếp từ nhà máy',heroProduct:'Giảm xóc ô tô',heroCertification:'Chứng nhận chất lượng',title:'Trung tâm sản phẩm',intro:'Phụ tùng gầm xe chất lượng cao, phù hợp nhiều dòng xe, không ngừng mở rộng.',introSecondary:en.intro,quality:'Ổn định, bền bỉ',qualitySecondary:en.quality,fitment:'Phù hợp nhiều dòng xe',fitmentSecondary:en.fitment,expansion:'Tiếp tục mở rộng sản phẩm',expansionSecondary:en.expansion,categoryTitles:['Giảm xóc ô tô','Hệ thống treo','Hệ thống lái','Hệ thống phanh','Cao su gầm xe','Sản phẩm khác'],shockTitle:'Giảm xóc ô tô',shockSubtitle:' / Shock Absorbers',shockDescription:en.shockSecondary,shockSecondary:en.shockDescription,byVehicle:'Tìm theo xe',byOem:'Tìm theo mã OEM',byPart:'Tìm theo mã sản phẩm',brand:'Chọn hãng xe',model:'Chọn dòng xe',year:'Chọn năm',brandExample:'Ví dụ: Toyota',modelExample:'Ví dụ: Vios',yearExample:'Ví dụ: 2014 – 2022',oem:'Mã OEM tham khảo',part:'Mã sản phẩm NEVERSTOP',oemExample:'Nhập mã OEM tham khảo',partExample:'Nhập mã sản phẩm NEVERSTOP',search:'Tìm sản phẩm',popular:'Giảm xóc cho dòng xe phổ biến',popularIntro:'Giảm xóc chất lượng cao cho các dòng xe phổ biến tại Việt Nam và toàn cầu',moreVehicles:'Xem thêm dòng xe',vehicleProduct:'Giảm xóc / Shock Absorber',moreCategories:'Sắp ra mắt thêm danh mục sản phẩm',moreIntro:en.moreIntro,moreSecondary:'Chúng tôi đang tiếp tục mở rộng các sản phẩm gầm xe. Hãy đón chờ!',follow:'Theo dõi để cập nhật sản phẩm mới'},
 ar:{...en,heroDirect:'مباشرة من المصنع',heroProduct:'ممتصات صدمات السيارات',heroCertification:'شهادة الجودة',title:'مركز المنتجات',intro:'قطع هيكل عالية الجودة لمجموعة واسعة من السيارات، مع توسيع مستمر للمنتجات.',introSecondary:en.intro,quality:'جودة موثوقة',qualitySecondary:en.quality,fitment:'توافق واسع',fitmentSecondary:en.fitment,expansion:'المزيد من المنتجات قريباً',expansionSecondary:en.expansion,categoryTitles:['ممتصات الصدمات','أجزاء التعليق','أجزاء التوجيه','أجزاء الفرامل','أجزاء مطاطية','منتجات أخرى'],shockTitle:'ممتصات الصدمات',shockSubtitle:' / Shock Absorbers / Giảm xóc ô tô',shockDescription:'تُصنع ممتصات صدمات NEVERSTOP بمواد عالية الجودة وعمليات دقيقة لتوفير ثبات القيادة والراحة والمتانة لمجموعة واسعة من السيارات.',shockSecondary:en.shockDescription,byVehicle:'البحث حسب السيارة',byOem:'البحث برقم OEM',byPart:'البحث برقم القطعة',brand:'اختر الماركة',model:'اختر الطراز',year:'اختر السنوات',brandExample:'مثال: Toyota',modelExample:'مثال: Vios',yearExample:'مثال: 2014 – 2022',oem:'مرجع OEM',part:'رقم قطعة NEVERSTOP',oemExample:'أدخل رقم OEM المرجعي',partExample:'أدخل رقم قطعة NEVERSTOP',search:'ابحث عن المنتجات',popular:'ممتصات صدمات للسيارات الشائعة',popularIntro:'ممتصات صدمات عالية الجودة للسيارات الشائعة في فيتنام والعالم',moreVehicles:'عرض المزيد من السيارات',vehicleProduct:'ممتص صدمات / Shock Absorber',moreCategories:'المزيد من فئات المنتجات قريباً',moreIntro:en.moreIntro,moreSecondary:'نواصل توسيع مجموعة قطع هيكل السيارات. ترقبوا الجديد!',follow:'تابعنا لمعرفة أحدث المنتجات'},
 es:{...en,heroDirect:'Directo de fábrica',heroProduct:'Amortiguadores de automóvil',heroCertification:'Certificación de calidad',title:'Centro de productos',intro:'Piezas de chasis de alta calidad para múltiples vehículos, en constante expansión.',introSecondary:en.intro,quality:'Calidad fiable',qualitySecondary:en.quality,fitment:'Amplia compatibilidad',fitmentSecondary:en.fitment,expansion:'Más productos próximamente',expansionSecondary:en.expansion,categoryTitles:['Amortiguadores','Suspensión','Dirección','Frenos','Piezas de caucho','Otros productos'],shockTitle:'Amortiguadores',shockSubtitle:' / Shock Absorbers / Giảm xóc ô tô',shockDescription:'Los amortiguadores NEVERSTOP se fabrican con materiales de alta calidad y procesos rigurosos para ofrecer estabilidad, comodidad y durabilidad en numerosos modelos.',shockSecondary:en.shockDescription,byVehicle:'Buscar por vehículo',byOem:'Buscar por número OEM',byPart:'Buscar por referencia',brand:'Seleccionar marca',model:'Seleccionar modelo',year:'Seleccionar años',brandExample:'Ej.: Toyota',modelExample:'Ej.: Vios',yearExample:'Ej.: 2014 – 2022',oem:'Referencia OEM',part:'Referencia NEVERSTOP',oemExample:'Introduce la referencia OEM',partExample:'Introduce la referencia NEVERSTOP',search:'Buscar productos',popular:'Amortiguadores para vehículos populares',popularIntro:'Amortiguadores de calidad para vehículos populares en Vietnam y el mundo',moreVehicles:'Ver más vehículos',vehicleProduct:'Amortiguador / Shock Absorber',moreCategories:'Más categorías de productos próximamente',moreIntro:en.moreIntro,moreSecondary:'Seguimos ampliando nuestra gama de piezas de chasis. ¡Mantente al tanto!',follow:'Síguenos para conocer las novedades'},
 pt:{...en,heroDirect:'Direto da fábrica',heroProduct:'Amortecedores automotivos',heroCertification:'Certificação de qualidade',title:'Centro de produtos',intro:'Peças de chassis de alta qualidade para vários veículos, em constante expansão.',introSecondary:en.intro,quality:'Qualidade fiável',qualitySecondary:en.quality,fitment:'Ampla compatibilidade',fitmentSecondary:en.fitment,expansion:'Mais produtos em breve',expansionSecondary:en.expansion,categoryTitles:['Amortecedores','Suspensão','Direção','Travões','Peças de borracha','Outros produtos'],shockTitle:'Amortecedores',shockSubtitle:' / Shock Absorbers / Giảm xóc ô tô',shockDescription:'Os amortecedores NEVERSTOP são fabricados com materiais de alta qualidade e processos rigorosos para oferecer estabilidade, conforto e durabilidade numa ampla gama de modelos.',shockSecondary:en.shockDescription,byVehicle:'Buscar por veículo',byOem:'Buscar por número OEM',byPart:'Buscar por referência',brand:'Selecionar marca',model:'Selecionar modelo',year:'Selecionar anos',brandExample:'Ex.: Toyota',modelExample:'Ex.: Vios',yearExample:'Ex.: 2014 – 2022',oem:'Referência OEM',part:'Referência NEVERSTOP',oemExample:'Introduza a referência OEM',partExample:'Introduza a referência NEVERSTOP',search:'Buscar produtos',popular:'Amortecedores para veículos populares',popularIntro:'Amortecedores de qualidade para veículos populares no Vietname e no mundo',moreVehicles:'Ver mais veículos',vehicleProduct:'Amortecedor / Shock Absorber',moreCategories:'Mais categorias de produtos em breve',moreIntro:en.moreIntro,moreSecondary:'Continuamos a expandir a nossa gama de peças de chassis. Fique atento!',follow:'Siga-nos para conhecer as novidades'},
};
export function productCenterCopy(locale:Locale){return copy[locale];}
export const productCenterCategories=[
 {id:'shocks',en:'Shock Absorbers',vi:'Giảm xóc ô tô'},
 {id:'suspension',en:'Suspension Parts',vi:'Hệ thống treo'},
 {id:'steering',en:'Steering Parts',vi:'Hệ thống lái'},
 {id:'brakes',en:'Brake Parts',vi:'Hệ thống phanh'},
 {id:'rubber',en:'Rubber Parts',vi:'Cao su gầm xe'},
 {id:'other',en:'Other Parts',vi:'Sản phẩm khác'},
];
// The customer's six reference cards are navigation shortcuts, never fabricated SKU recommendations.
export const productCenterVehicles=[
 {brand:'Toyota',model:'Vios',image:'vios',referenceYears:'2014 – 2022'},
 {brand:'Mitsubishi',model:'Xpander',image:'xpander',referenceYears:'2018 – 2024'},
 {brand:'Ford',model:'Ranger',image:'ranger',referenceYears:'2012 – 2024'},
 {brand:'Toyota',model:'Fortuner',image:'fortuner',referenceYears:'2015 – 2024'},
 {brand:'Toyota',model:'Innova',image:'innova',referenceYears:'2016 – 2024'},
 {brand:'Hyundai',model:'Grand i10',image:'i10',referenceYears:'2014 – 2023'},
];
