import type {Locale} from './i18n';

const en={
  home:'Home',products:'Products',partNumber:'NEVERSTOP Part Number',referenceOem:'Reference OEM',
  oemNote:'Reference OEM numbers are provided for fitment identification only.',
  oemScope:'OEM references belong to this product. The database does not specify an OEM-to-vehicle-row mapping.',
  brand:'Vehicle Brand',model:'Vehicle Model',generation:'Generation / Chassis',year:'Year Range',engine:'Engine',
  axle:'Axle',position:'Installation Position',productName:'Product Name',productType:'Product Type',unit:'Unit',stock:'Stock Status',
  hanoiStock:'Hanoi Stock',confirmStock:'Contact to Confirm Stock',requestQuote:'Request Quote',confirmFitment:'Confirm Fitment',
  fitmentNote:'Confirm the vehicle, year, reference OEM and installation position before ordering.',
  zaloContact:'Vietnam customers · Zalo',whatsappContact:'Overseas customers · WhatsApp',
  productInformation:'Product Information',technicalData:'Technical Data',vehicleFitment:'Vehicle Fitment',packaging:'Packaging & Logistics',relatedProducts:'Related Products',
  extendedLength:'Extended Length',compressedLength:'Compressed Length',stroke:'Stroke',pistonRodDiameter:'Piston Rod Diameter',bodyDiameter:'Body Diameter',upperMount:'Upper Mount',lowerMount:'Lower Mount',shockType:'Shock Type',netWeight:'Net Weight',grossWeight:'Gross Weight',perCarton:'Qty per Carton',piecesPerBox:'Pieces per Box',cartonSize:'Carton Size',
  description:'Product Description',photoPending:'Product photos to be added',selectPhoto:'View product photo {number}',previousPhoto:'Previous photo',nextPhoto:'Next photo',gallery:'Product photos',onward:'onward',front:'Front',rear:'Rear',other:'Other',left:'Left',right:'Right',both:'Both sides',shockAbsorber:'Shock Absorber',viewProduct:'View product',moreFitments:'See all vehicle fitments',
};
export type ProductDetailCopy=typeof en;
const zh:ProductDetailCopy={
  home:'首页',products:'产品',partNumber:'NEVERSTOP 产品编号',referenceOem:'OEM 参考号',
  oemNote:'OEM 号码仅用于车型与产品适配核对。',oemScope:'这些 OEM 为产品级参考号，数据库尚未提供逐车型的 OEM 对应关系。',
  brand:'汽车品牌',model:'车型',generation:'代际 / 底盘代号',year:'适配年份',engine:'发动机',axle:'安装轴',position:'安装位置',productName:'产品名称',productType:'产品类型',unit:'销售单位',stock:'库存状态',
  hanoiStock:'河内门店有货',confirmStock:'联系确认库存',requestQuote:'获取报价',confirmFitment:'确认适配',fitmentNote:'订购前请确认车型、年份、OEM 参考号及安装位置。',
  zaloContact:'越南客户 · Zalo 咨询',whatsappContact:'海外客户 · WhatsApp 咨询',productInformation:'产品信息',technicalData:'技术参数',vehicleFitment:'适配车型',packaging:'包装与物流',relatedProducts:'相关产品',
  extendedLength:'伸展长度',compressedLength:'压缩长度',stroke:'行程',pistonRodDiameter:'活塞杆直径',bodyDiameter:'筒体直径',upperMount:'上安装点',lowerMount:'下安装点',shockType:'减震器类型',netWeight:'净重',grossWeight:'毛重',perCarton:'每箱数量',piecesPerBox:'单盒数量',cartonSize:'外箱尺寸',
  description:'产品说明',photoPending:'产品图片待补充',selectPhoto:'查看第 {number} 张产品图',previousPhoto:'上一张产品图',nextPhoto:'下一张产品图',gallery:'产品图片',onward:'起',front:'前轴',rear:'后轴',other:'其他',left:'左侧',right:'右侧',both:'左右两侧',shockAbsorber:'汽车减震器',viewProduct:'查看产品',moreFitments:'查看全部适配车型',
};
const vi:ProductDetailCopy={
  home:'Trang chủ',products:'Sản phẩm',partNumber:'Mã sản phẩm NEVERSTOP',referenceOem:'Mã OEM tham chiếu',
  oemNote:'Mã OEM chỉ được cung cấp để đối chiếu khả năng phù hợp của sản phẩm với xe.',oemScope:'Các mã OEM thuộc sản phẩm này. Cơ sở dữ liệu chưa có liên kết OEM với từng dòng xe.',
  brand:'Hãng xe',model:'Mẫu xe',generation:'Thế hệ / Mã khung gầm',year:'Năm sản xuất phù hợp',engine:'Động cơ',axle:'Cầu xe',position:'Vị trí lắp đặt',productName:'Tên sản phẩm',productType:'Loại sản phẩm',unit:'Đơn vị',stock:'Tình trạng tồn kho',
  hanoiStock:'Có hàng tại Hà Nội',confirmStock:'Liên hệ xác nhận tồn kho',requestQuote:'Yêu cầu báo giá',confirmFitment:'Xác nhận phù hợp',fitmentNote:'Vui lòng xác nhận mẫu xe, năm sản xuất, mã OEM tham chiếu và vị trí lắp trước khi đặt hàng.',
  zaloContact:'Khách Việt Nam · Tư vấn Zalo',whatsappContact:'Khách quốc tế · WhatsApp',productInformation:'Thông tin sản phẩm',technicalData:'Thông số kỹ thuật',vehicleFitment:'Phù hợp với dòng xe',packaging:'Đóng gói & Vận chuyển',relatedProducts:'Sản phẩm liên quan',
  extendedLength:'Chiều dài khi giãn',compressedLength:'Chiều dài khi nén',stroke:'Hành trình',pistonRodDiameter:'Đường kính ty piston',bodyDiameter:'Đường kính thân',upperMount:'Liên kết trên',lowerMount:'Liên kết dưới',shockType:'Loại giảm xóc',netWeight:'Khối lượng tịnh',grossWeight:'Khối lượng cả bì',perCarton:'Số lượng mỗi thùng',piecesPerBox:'Số sản phẩm mỗi hộp',cartonSize:'Kích thước thùng',
  description:'Mô tả sản phẩm',photoPending:'Ảnh sản phẩm đang được bổ sung',selectPhoto:'Xem ảnh sản phẩm {number}',previousPhoto:'Ảnh trước',nextPhoto:'Ảnh tiếp theo',gallery:'Ảnh sản phẩm',onward:'trở đi',front:'Trước',rear:'Sau',other:'Khác',left:'Trái',right:'Phải',both:'Hai bên',shockAbsorber:'Giảm xóc ô tô',viewProduct:'Xem sản phẩm',moreFitments:'Xem tất cả dòng xe phù hợp',
};
const ar:ProductDetailCopy={
  home:'الرئيسية',products:'المنتجات',partNumber:'رقم قطعة NEVERSTOP',referenceOem:'أرقام OEM المرجعية',oemNote:'تُقدَّم أرقام OEM المرجعية للتحقق من توافق القطعة مع السيارة فقط.',oemScope:'تخص أرقام OEM هذا المنتج؛ لا تحدد قاعدة البيانات رقم OEM لكل صف سيارة.',
  brand:'ماركة السيارة',model:'طراز السيارة',generation:'الجيل / رمز الهيكل',year:'سنوات التوافق',engine:'المحرك',axle:'المحور',position:'موضع التركيب',productName:'اسم المنتج',productType:'نوع المنتج',unit:'الوحدة',stock:'حالة المخزون',hanoiStock:'متوفر في هانوي',confirmStock:'تواصل لتأكيد المخزون',requestQuote:'طلب عرض سعر',confirmFitment:'تأكيد التوافق',fitmentNote:'تحقق من الطراز والسنة ورقم OEM المرجعي وموضع التركيب قبل الطلب.',
  zaloContact:'عملاء فيتنام · Zalo',whatsappContact:'العملاء الدوليون · WhatsApp',productInformation:'معلومات المنتج',technicalData:'البيانات الفنية',vehicleFitment:'توافق السيارات',packaging:'التغليف والشحن',relatedProducts:'منتجات ذات صلة',extendedLength:'الطول عند التمدد',compressedLength:'الطول عند الانضغاط',stroke:'الشوط',pistonRodDiameter:'قطر قضيب المكبس',bodyDiameter:'قطر الجسم',upperMount:'التثبيت العلوي',lowerMount:'التثبيت السفلي',shockType:'نوع ممتص الصدمات',netWeight:'الوزن الصافي',grossWeight:'الوزن الإجمالي',perCarton:'الكمية في الكرتون',piecesPerBox:'القطع في العلبة',cartonSize:'أبعاد الكرتون',description:'وصف المنتج',photoPending:'ستُضاف صور المنتج لاحقاً',selectPhoto:'عرض صورة المنتج {number}',previousPhoto:'الصورة السابقة',nextPhoto:'الصورة التالية',gallery:'صور المنتج',onward:'فصاعداً',front:'أمامي',rear:'خلفي',other:'أخرى',left:'يسار',right:'يمين',both:'الجانبان',shockAbsorber:'ممتص صدمات',viewProduct:'عرض المنتج',moreFitments:'عرض جميع السيارات المتوافقة',
};
const es:ProductDetailCopy={
  home:'Inicio',products:'Productos',partNumber:'Referencia NEVERSTOP',referenceOem:'Referencias OEM',oemNote:'Las referencias OEM se proporcionan únicamente para identificar la compatibilidad.',oemScope:'Las referencias OEM corresponden al producto. La base de datos no las vincula con cada fila de vehículos.',brand:'Marca del vehículo',model:'Modelo',generation:'Generación / Chasis',year:'Años compatibles',engine:'Motor',axle:'Eje',position:'Posición de montaje',productName:'Nombre del producto',productType:'Tipo de producto',unit:'Unidad',stock:'Disponibilidad',hanoiStock:'Disponible en Hanói',confirmStock:'Consultar disponibilidad',requestQuote:'Solicitar cotización',confirmFitment:'Confirmar compatibilidad',fitmentNote:'Confirme el vehículo, el año, la referencia OEM y la posición de montaje antes de pedir.',zaloContact:'Clientes en Vietnam · Zalo',whatsappContact:'Clientes internacionales · WhatsApp',productInformation:'Información del producto',technicalData:'Datos técnicos',vehicleFitment:'Compatibilidad con vehículos',packaging:'Embalaje y logística',relatedProducts:'Productos relacionados',extendedLength:'Longitud extendida',compressedLength:'Longitud comprimida',stroke:'Recorrido',pistonRodDiameter:'Diámetro del vástago',bodyDiameter:'Diámetro del cuerpo',upperMount:'Anclaje superior',lowerMount:'Anclaje inferior',shockType:'Tipo de amortiguador',netWeight:'Peso neto',grossWeight:'Peso bruto',perCarton:'Cantidad por caja exterior',piecesPerBox:'Piezas por caja',cartonSize:'Dimensiones de caja exterior',description:'Descripción del producto',photoPending:'Fotos del producto pendientes',selectPhoto:'Ver foto del producto {number}',previousPhoto:'Foto anterior',nextPhoto:'Foto siguiente',gallery:'Fotos del producto',onward:'en adelante',front:'Delantero',rear:'Trasero',other:'Otro',left:'Izquierda',right:'Derecha',both:'Ambos lados',shockAbsorber:'Amortiguador',viewProduct:'Ver producto',moreFitments:'Ver todos los vehículos compatibles',
};
const pt:ProductDetailCopy={
  home:'Início',products:'Produtos',partNumber:'Referência NEVERSTOP',referenceOem:'Referências OEM',oemNote:'Os números OEM de referência servem apenas para identificar a compatibilidade.',oemScope:'As referências OEM pertencem ao produto. A base de dados não as associa a cada linha de veículos.',brand:'Marca do veículo',model:'Modelo',generation:'Geração / Chassi',year:'Anos compatíveis',engine:'Motor',axle:'Eixo',position:'Posição de instalação',productName:'Nome do produto',productType:'Tipo de produto',unit:'Unidade',stock:'Disponibilidade',hanoiStock:'Disponível em Hanói',confirmStock:'Contacte para confirmar o stock',requestQuote:'Solicitar orçamento',confirmFitment:'Confirmar compatibilidade',fitmentNote:'Confirme o veículo, o ano, a referência OEM e a posição de instalação antes de encomendar.',zaloContact:'Clientes no Vietname · Zalo',whatsappContact:'Clientes internacionais · WhatsApp',productInformation:'Informações do produto',technicalData:'Dados técnicos',vehicleFitment:'Compatibilidade com veículos',packaging:'Embalagem e logística',relatedProducts:'Produtos relacionados',extendedLength:'Comprimento estendido',compressedLength:'Comprimento comprimido',stroke:'Curso',pistonRodDiameter:'Diâmetro da haste',bodyDiameter:'Diâmetro do corpo',upperMount:'Fixação superior',lowerMount:'Fixação inferior',shockType:'Tipo de amortecedor',netWeight:'Peso líquido',grossWeight:'Peso bruto',perCarton:'Quantidade por caixa exterior',piecesPerBox:'Peças por caixa',cartonSize:'Dimensões da caixa exterior',description:'Descrição do produto',photoPending:'Fotografias do produto por adicionar',selectPhoto:'Ver fotografia do produto {number}',previousPhoto:'Fotografia anterior',nextPhoto:'Fotografia seguinte',gallery:'Fotografias do produto',onward:'em diante',front:'Dianteiro',rear:'Traseiro',other:'Outro',left:'Esquerda',right:'Direita',both:'Ambos os lados',shockAbsorber:'Amortecedor',viewProduct:'Ver produto',moreFitments:'Ver todos os veículos compatíveis',
};
const copies:Record<Locale,ProductDetailCopy>={en,zh,vi,ar,es,pt};
const presentation={
  en:{zoomPhoto:'Enlarge product photo',close:'Close',temporaryPhoto:'Temporary reference photography',copyPartNumber:'Copy part number',copied:'Part number copied',copyUnavailable:'Select the part number to copy it',packagingPhoto:'Packaging photography',temporaryPackaging:'Temporary packaging reference images',frontShock:'Front Shock Absorber',rearShock:'Rear Shock Absorber',zaloSub:'Tư vấn qua Zalo',whatsappSub:'Chat on WhatsApp'},
  zh:{zoomPhoto:'放大产品图',close:'关闭',temporaryPhoto:'临时参考产品图',copyPartNumber:'复制产品编号',copied:'产品编号已复制',copyUnavailable:'请选择产品编号并复制',packagingPhoto:'包装图片',temporaryPackaging:'临时参考包装图片',frontShock:'前减震器',rearShock:'后减震器',zaloSub:'Tư vấn qua Zalo',whatsappSub:'Chat on WhatsApp'},
  vi:{zoomPhoto:'Phóng to ảnh sản phẩm',close:'Đóng',temporaryPhoto:'Ảnh tham khảo tạm thời',copyPartNumber:'Sao chép mã sản phẩm',copied:'Đã sao chép mã sản phẩm',copyUnavailable:'Chọn mã sản phẩm để sao chép',packagingPhoto:'Ảnh đóng gói',temporaryPackaging:'Ảnh đóng gói tham khảo tạm thời',frontShock:'Giảm xóc trước',rearShock:'Giảm xóc sau',zaloSub:'Tư vấn qua Zalo',whatsappSub:'Chat on WhatsApp'},
  ar:{zoomPhoto:'تكبير صورة المنتج',close:'إغلاق',temporaryPhoto:'صور مرجعية مؤقتة',copyPartNumber:'نسخ رقم القطعة',copied:'تم نسخ رقم القطعة',copyUnavailable:'حدد رقم القطعة لنسخه',packagingPhoto:'صور التغليف',temporaryPackaging:'صور تغليف مرجعية مؤقتة',frontShock:'ممتص صدمات أمامي',rearShock:'ممتص صدمات خلفي',zaloSub:'Tư vấn qua Zalo',whatsappSub:'Chat on WhatsApp'},
  es:{zoomPhoto:'Ampliar foto del producto',close:'Cerrar',temporaryPhoto:'Fotografía de referencia temporal',copyPartNumber:'Copiar referencia',copied:'Referencia copiada',copyUnavailable:'Seleccione la referencia para copiarla',packagingPhoto:'Fotos del embalaje',temporaryPackaging:'Fotos de embalaje de referencia temporal',frontShock:'Amortiguador delantero',rearShock:'Amortiguador trasero',zaloSub:'Tư vấn qua Zalo',whatsappSub:'Chat on WhatsApp'},
  pt:{zoomPhoto:'Ampliar fotografia do produto',close:'Fechar',temporaryPhoto:'Fotografia de referência temporária',copyPartNumber:'Copiar referência',copied:'Referência copiada',copyUnavailable:'Selecione a referência para a copiar',packagingPhoto:'Fotografias da embalagem',temporaryPackaging:'Fotografias de embalagem de referência temporárias',frontShock:'Amortecedor dianteiro',rearShock:'Amortecedor traseiro',zaloSub:'Tư vấn qua Zalo',whatsappSub:'Chat on WhatsApp'},
};
export function productDetailCopy(locale:Locale){return {...copies[locale],...presentation[locale]};}
