// Presentation metadata only. Active brands and model options always come from /api/vehicles.
// These optional fields can move to VehicleBrand later without changing the wall contract.
export type BrandPresentation = {logoUrl?:string;logoAlt?:string;displayOrder:number;isFeatured:boolean};
export const brandPriority = ['Toyota','Hyundai','Kia','Mitsubishi','Ford','Mazda','Honda','Suzuki','Nissan','Isuzu','Mercedes-Benz','BMW','Audi','Volkswagen','Volvo','Peugeot','Subaru','Lexus','BYD','Geely','Lynk & Co','Chery','Omoda','Jaecoo','MG','GAC','Haval','VinFast','Tesla'];
export const brandKey=(name:string)=>name.toLowerCase().replace(/[^a-z0-9]/g,'');
const files:Record<string,string>={Toyota:'toyota-logo.svg',Hyundai:'hyundai-logo.svg',Ford:'ford-logo.svg',BMW:'bmw-logo.svg',BYD:'byd-logo.svg',Geely:'geely-logo.svg',VinFast:'vinfast-logo.svg',Tesla:'tesla-logo.svg'};
const futureLogoFiles:Record<string,string>={"Toyota": "toyota-logo.svg", "Hyundai": "hyundai-logo.svg", "Kia": "kia-logo.svg", "Mitsubishi": "mitsubishi-logo.svg", "Ford": "ford-logo.png", "Mazda": "mazda-logo.svg", "Honda": "honda-logo.png", "Suzuki": "suzuki-logo.svg", "Nissan": "nissan-logo.svg", "Isuzu": "isuzu-logo.svg", "Mercedes-Benz": "mercedes-benz-logo.svg", "BMW": "bmw-logo.svg", "Audi": "audi-logo.svg", "Volkswagen": "volkswagen-logo.svg", "Volvo": "volvo-logo.svg", "Peugeot": "peugeot-logo.svg", "Subaru": "subaru-logo.png", "Lexus": "lexus-logo.png", "BYD": "byd-logo.svg", "Geely": "geely-logo.svg", "Chery": "chery-logo.png", "Omoda": "omoda-logo.png", "Jaecoo": "jaecoo-logo.svg", "MG": "mg-logo.png", "Haval": "haval-logo.png", "VinFast": "vinfast-logo.png", "Tesla": "tesla-logo.svg"};
export const brandLogoMapping:Record<string,BrandPresentation>=Object.fromEntries(brandPriority.map((name,i)=>[brandKey(name),{logoUrl:files[name]?`/brands/vehicles/${files[name]}`:futureLogoFiles[name]?`https://cdn.jsdelivr.net/gh/vehiclespecs/brand-logos@main/${futureLogoFiles[name]}`:undefined,logoAlt:`${name} logo`,displayOrder:i,isFeatured:true}]));
// Small, explicit roadmap preview, never inserted into the database or selection list.
export const plannedBrandPreview=['Hyundai','Ford','BMW','BYD','Geely','VinFast','Tesla'];
