'use client';
import {zaloChannels} from '@/lib/zalo-config';
import {useState} from 'react';
import {formatMoney,post} from './common';
type Product={id:string;partNumber:string;nameVi:string;nameEn?:string;nameZh?:string};
type Item={productId:string;partNumber:string;productName:string;quantity:number;unitPrice:number};
type Fields={customerType:'B2B'|'B2C';customerName:string;phone:string;zalo:string;city:string;address:string;vehicleBrand:string;vehicleModel:string;vehicleYear:string;vehicleCode:string;shippingFee:number;discount:number;validUntil:string;warrantyTermsSnapshot:string;customerNote:string;internalNote:string;codEligible:boolean;onlinePaymentEnabled:boolean};
export type EditorValue=Fields&{items:Item[]};
const defaults:Fields={customerType:'B2C',customerName:'',phone:'',zalo:'',city:'',address:'',vehicleBrand:'',vehicleModel:'',vehicleYear:'',vehicleCode:'',shippingFee:0,discount:0,validUntil:'',warrantyTermsSnapshot:'',customerNote:'',internalNote:'',codEligible:false,onlinePaymentEnabled:false};
const labels:Record<string,string>={customerName:'Tên khách hàng',phone:'Số điện thoại',zalo:'Zalo khách hàng',city:'Tỉnh / Thành phố',address:'Địa chỉ',vehicleBrand:'Hãng xe',vehicleModel:'Dòng xe',vehicleYear:'Năm sản xuất',vehicleCode:'Mã xe',shippingFee:'Phí vận chuyển (₫)',discount:'Giảm giá (₫)',validUntil:'Hiệu lực đến',warrantyTermsSnapshot:'Điều kiện bảo hành (bản lưu cố định)',customerNote:'Ghi chú cho khách hàng',internalNote:'Ghi chú nội bộ (không hiển thị cho khách)'};
export default function QuoteEditor({initial,revisionId,customerType='B2C',prefill}:{initial?:EditorValue;revisionId?:string;customerType?:'B2B'|'B2C';prefill?:Partial<Fields>}){const [fields,setFields]=useState<Fields>(initial||{...defaults,customerType,...prefill}),[items,setItems]=useState<Item[]>(initial?.items||[]),[query,setQuery]=useState(''),[products,setProducts]=useState<Product[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const subtotal=items.reduce((n,i)=>n+i.quantity*i.unitPrice,0);async function search(){try{const r=await fetch('/api/products?q='+encodeURIComponent(query));const b=await r.json();if(!r.ok)throw new Error('Không tìm được sản phẩm.');setProducts(b.data);}catch(e){setError((e as Error).message);}}
 return <form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{const data={...fields,validUntil:new Date(fields.validUntil).toISOString(),items:items.map(({productId,quantity,unitPrice})=>({productId,quantity,unitPrice}))};const q=await post(revisionId?`/api/admin/quotes/${revisionId}`:'/api/admin/quotes',revisionId?{action:'revise',quote:data}:data);location.href='/admin/quotes/'+q.id;}catch(e){setError((e as Error).message);setBusy(false);}}}>
 <h1>{revisionId?'Tạo phiên bản báo giá mới':'Tạo báo giá'}</h1><p className="muted">Giá bán do nhân viên xác nhận sau khi trao đổi qua Zalo. Không tạo đơn hàng khi lưu báo giá.</p><section className="panel"><h2>Khách hàng & xe</h2><label>Loại khách hàng<select value={fields.customerType} onChange={e=>setFields({...fields,customerType:e.target.value as 'B2B'|'B2C'})}><option value="B2B">B2B · Gara / Cửa hàng / Đại lý · {zaloChannels.B2B.phone}</option><option value="B2C">B2C · Chủ xe · {zaloChannels.B2C.phone}</option></select></label><div className="grid">{(['customerName','phone','zalo','city','address','vehicleBrand','vehicleModel','vehicleYear','vehicleCode'] as const).map(key=><label key={key}>{labels[key]}<input value={fields[key]} required={key==='customerName'||key==='phone'} maxLength={500} onChange={e=>setFields({...fields,[key]:e.target.value})}/></label>)}</div></section>
 <section className="panel"><h2>Sản phẩm</h2><label>Tìm theo mã NEVERSTOP / OE / tên<input value={query} onChange={e=>setQuery(e.target.value)}/></label><button type="button" onClick={search}>Tìm sản phẩm</button><div>{products.map(p=><div key={p.id} className="item">{p.partNumber} · {p.nameVi}<button type="button" onClick={()=>{if(items.some(i=>i.productId===p.id))return;setItems([...items,{productId:p.id,partNumber:p.partNumber,productName:p.nameVi,quantity:1,unitPrice:0}]);}}>Thêm vào báo giá</button></div>)}</div>{items.map((item,index)=><div className="item" key={item.productId}><h3>{item.partNumber} · {item.productName}</h3><div className="grid"><label>Số lượng<input type="number" min="1" max="10000" required value={item.quantity} onChange={e=>setItems(items.map((v,j)=>j===index?{...v,quantity:Number(e.target.value)}:v))}/></label><label>Đơn giá thực tế (₫)<input type="number" min="0" max="99999999999" required value={item.unitPrice} onChange={e=>setItems(items.map((v,j)=>j===index?{...v,unitPrice:Number(e.target.value)}:v))}/></label></div><p>{formatMoney(item.quantity*item.unitPrice)}</p><button type="button" onClick={()=>setItems(items.filter((_,j)=>j!==index))}>Bỏ sản phẩm</button></div>)}</section>
 <section className="panel"><h2>Điều kiện giao dịch</h2><div className="grid">{(['shippingFee','discount'] as const).map(key=><label key={key}>{labels[key]}<input type="number" min="0" required value={fields[key]} onChange={e=>setFields({...fields,[key]:Number(e.target.value)})}/></label>)}<label>{labels.validUntil}<input type="datetime-local" required value={fields.validUntil} onChange={e=>setFields({...fields,validUntil:e.target.value})}/></label></div>{(['warrantyTermsSnapshot','customerNote','internalNote'] as const).map(key=><label key={key}>{labels[key]}<textarea required={key==='warrantyTermsSnapshot'} maxLength={key==='warrantyTermsSnapshot'?12000:3000} value={fields[key]} onChange={e=>setFields({...fields,[key]:e.target.value})}/></label>)}<p><label><input type="checkbox" checked={fields.codEligible} onChange={e=>setFields({...fields,codEligible:e.target.checked})}/>Cho phép COD</label></p><p><label><input type="checkbox" checked={fields.onlinePaymentEnabled} onChange={e=>setFields({...fields,onlinePaymentEnabled:e.target.checked})}/>Cho phép thanh toán QR (hiện tại chỉ TEST)</label></p><p className="total">{formatMoney(subtotal+fields.shippingFee-fields.discount)}</p><p className="muted">Tổng sẽ được tính lại tại máy chủ khi lưu.</p></section>{error&&<p role="alert" className="error">{error}</p>}<div className="form-actions"><button disabled={busy||!items.length}>{busy?'Đang lưu…':'Lưu bản nháp'}</button></div></form>;
}
