'use client';
import Link from 'next/link';
import {useState} from 'react';
import {post,formatMoney} from './common';
import {ZaloChatButton} from '@/components/zalo-contact';
import type {getPublicQuote} from '@/lib/commerce/service';
type Quote=Awaited<ReturnType<typeof getPublicQuote>>;
export default function QuoteClient({q,token}:{q:Quote;token:string}){const [consent,setConsent]=useState(false),[cod,setCod]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');const closed=['EXPIRED','CANCELLED'].includes(q.status),complete=['PAID','COD_CONFIRMED'].includes(q.status);
 async function action(path:string,data:unknown){setBusy(true);setError('');try{const result=await post(path,data);if(result.paymentToken)location.href='/payment/'+result.paymentToken;else if(result.orderToken)location.href='/order/'+result.orderToken;else location.reload();}catch(e){setError((e as Error).message);setBusy(false);}}
 return <><header><Link href="/vi">NEVERSTOP FACTORY-DIRECT</Link><span>BÁO GIÁ</span></header><h1>{q.quoteNumber}</h1><p className="status">{q.status}</p><p>{q.customerName} · {q.customerType==='B2B'?'Gara / Cửa hàng / Đại lý':'Chủ xe'}</p><p>{q.vehicleBrand} {q.vehicleModel} · {q.vehicleYear} · {q.vehicleCode}</p><p className="muted">Có hiệu lực đến: {new Date(q.validUntil).toLocaleString('vi-VN',{timeZone:'Asia/Ho_Chi_Minh'})}</p><section className="panel"><h2>Sản phẩm</h2>{q.items.map((i,index)=><article className="item" key={index}><p className="muted">{i.partNumber}</p><h3>{i.productName}</h3><p>OE: {i.oeNumber||'—'}</p><p>{i.vehicleInfo} · {i.axle||''} / {i.side||''}</p><div className="summary"><span>Số lượng: {i.quantity}</span><span>{formatMoney(i.unitPrice)} / sản phẩm</span></div><p>{formatMoney(i.lineTotal)}</p></article>)}<div className="summary"><span>Tiền hàng</span><span>{formatMoney(q.subtotal)}</span></div><div className="summary"><span>Phí vận chuyển</span><span>{formatMoney(q.shippingFee)}</span></div><div className="summary"><span>Giảm giá</span><span>− {formatMoney(q.discount)}</span></div><h2>TỔNG THANH TOÁN</h2><p className="total">{formatMoney(q.totalAmount)}</p></section><section className="panel"><h2>CHÍNH SÁCH BẢO HÀNH</h2><div className="warranty" tabIndex={0}>{q.warrantyTermsSnapshot}</div>{q.customerNote&&<p>{q.customerNote}</p>}</section>
 {closed?<section className="error"><h2>{q.status==='EXPIRED'?'Báo giá đã hết hạn.':'Báo giá đã hủy.'}</h2><p>Vui lòng liên hệ NEVERSTOP để cập nhật báo giá.</p></section>:complete?<section className="panel"><h2>{q.status==='PAID'?(q.isMockPayment?'THANH TOÁN THÀNH CÔNG · TEST':'THANH TOÁN THÀNH CÔNG'):'ĐƠN HÀNG ĐÃ ĐƯỢC XÁC NHẬN'}</h2>{q.isMockPayment&&<p className="test">TEST MODE · Thanh toán mô phỏng. Không có tiền thật được nhận.</p>}<a className="action" href={'/order/'+q.orderToken}>Xem đơn hàng · {q.orderNumber}</a></section>:!q.acceptedAt?<section className="panel"><label><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/>Tôi đã đọc và đồng ý với báo giá và chính sách bảo hành.</label><p><button disabled={!consent||busy} onClick={()=>action(`/api/quotes/${token}/accept`,{consent})}>ĐỒNG Ý BÁO GIÁ</button></p></section>:<section className="panel"><h2>PHƯƠNG THỨC THANH TOÁN</h2><p>Đã chấp nhận báo giá và chính sách bảo hành.</p>{q.onlinePaymentEnabled&&<button disabled={busy} onClick={()=>action('/api/payments/create',{token})}>THANH TOÁN QR · TEST</button>}{q.codEligible&&<button disabled={busy} onClick={()=>setCod(!cod)}>THANH TOÁN KHI NHẬN HÀNG · COD</button>}{!q.codEligible&&!q.onlinePaymentEnabled&&<p>Vui lòng liên hệ NEVERSTOP để xác nhận phương thức thanh toán.</p>}{cod&&<form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void action(`/api/quotes/${token}/cod`,Object.fromEntries(f));}}><h2>Xác nhận địa chỉ nhận hàng</h2><label>Tên người nhận<input name="name" required defaultValue={q.customerName}/></label><label>Số điện thoại<input name="phone" required defaultValue={q.phone} inputMode="tel"/></label><label>Tỉnh / Thành phố<input name="city" required defaultValue={q.city||''}/></label><label>Địa chỉ chi tiết<input name="address" required minLength={8} defaultValue={q.address||''}/></label><label>Ghi chú<textarea name="note"/></label><button disabled={busy}>XÁC NHẬN COD · {formatMoney(q.totalAmount)}</button></form>}</section>}
 {error&&<p className="error" role="alert">{error}</p>}<ZaloChatButton customerType={q.customerType} label="Liên hệ lại qua Zalo"/></>;
}
