import SocialIcon from './social-icon';
import {zaloChannels,contactCopy} from '@/lib/zalo-config';
import {socialLinks} from '@/lib/social-config';
import ZaloContact, {HeroContacts} from './zalo-contact';
import BrandIcon from './brand-icon';
import '@/app/factory.css';
import Link from 'next/link';
import Image from 'next/image';
import { Suspense } from 'react';
import type { Locale } from '@/lib/i18n';
import { homeCopy } from '@/lib/home-copy';
import { contacts, address } from '@/lib/site-config';
import VehicleSearch from './vehicle-search';
const maps = 'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent('183 Lạc Nghiệp, Bạch Mai, Hà Nội, Vietnam');
const vehicles = ['Toyota Vios','Toyota Camry','Toyota Corolla Altis','Toyota Fortuner','Hyundai Grand i10','Kia Morning'];
export default function FactoryHome({locale}:{locale:Locale}) {
 const c=homeCopy[locale];
 return <main id="main" className="factory-home">
 <div className="store-strip"><div><span className="status-dot"/><strong>{c.visit}</strong><span className="strip-address">{address}</span></div><div><div className="header-contacts">{contacts.map(v=><div className="header-contact" key={v.phone}><strong>{v.audience[locale]}</strong>{v.callEnabled?<a href={v.phoneHref}>{v.phone}</a>:<span>{v.phone}</span>}<a href={v.zaloHref} target="_blank" rel="noopener noreferrer"><BrandIcon name="Zalo" size={22}/> Zalo ↗</a></div>)}</div><a className="maps-link" href={maps} target="_blank" rel="noopener noreferrer" aria-label={`${c.directions} · Google Maps`} title="Google Maps"><BrandIcon name="Google Maps" size={26}/><span>{c.directions} ↗</span></a></div></div>
 <section className="factory-hero"><div className="hero-copy"><p className="eyebrow">{c.tag}</p><h1>{c.title}<br/><em>{c.accent}</em></h1><p className="hero-intro">{c.intro}</p><div className="actions"><Link className="button primary" href={`/${locale}/products`}>{c.explore} <span>↗</span></Link></div></div><div className="hero-photo"><Image src="/images/camry-shocks.jpg" alt={`${c.front} NEVERSTOP Toyota Camry ACV40`} fill priority sizes="(max-width: 760px) 100vw, 55vw"/><span className="photo-label">SHOCK ABSORBERS / NEVERSTOP</span><div className="photo-caption"><span>{c.real}</span><b>01 — 04</b></div></div><div className="hero-bottom"><HeroContacts locale={locale}/><div className="compact-finder hero-finder"><Suspense fallback={<p>…</p>}><VehicleSearch locale={locale} compact/></Suspense></div></div></section>
 <section className="home-section product-section"><div className="section-top"><div><p className="eyebrow">{c.productTag}</p><h2>{c.productTitle}</h2></div><p>{c.productBody}</p></div><div className="product-editorial"><Link href={`/${locale}/products?axle=FRONT`} className="product-feature"><div className="product-image"><Image src="/images/camry-shocks.jpg" alt={c.front} fill sizes="(max-width:760px) 100vw, 60vw"/></div><div className="product-meta"><div><span>NEVERSTOP / SHOCK ABSORBER</span><h3>{c.front}</h3></div><b>↗</b></div></Link><div className="product-side"><Link href={`/${locale}/products`}><div className="detail-image"><Image src="/images/shock-detail.jpg" alt={c.details} fill sizes="(max-width:760px) 100vw, 35vw"/></div><div className="product-meta"><div><span>NEVERSTOP / COLLECTION</span><h3>{c.details}</h3></div><b>↗</b></div></Link><a className="fitment-note" href="#contact">{c.check}<span>↗</span></a></div></div></section>
 <section className="home-section popular-section"><div className="section-top"><div><p className="eyebrow">{c.popularTag}</p><h2>{c.popularTitle}</h2></div><p>{c.popularBody}</p></div><div className="vehicle-links">{vehicles.map((name,i)=><Link key={name} href={`/${locale}/products?q=${encodeURIComponent(name.replace(/^(Toyota|Hyundai|Kia) /,''))}&search=1`}><small>0{i+1}</small><span>{name}</span><b>↗</b></Link>)}</div></section>
 <section className="road-section"><Image src="/images/camry.jpg" alt="Toyota Camry ACV40" fill sizes="100vw"/><div className="road-shade"/><div className="road-copy"><p className="eyebrow">{c.sceneTag}</p><h2>{c.sceneTitle}</h2><p>{c.sceneBody}</p><a className="button primary" href="#contact">{c.sceneCta} ↗</a></div><small>{c.reference}</small></section>
 <section className="home-section process-section"><div className="section-top"><div><p className="eyebrow">{c.processTag}</p><h2>{c.processTitle}</h2></div><p>{c.processBody}</p></div><div className="process-grid">{['factory','warehouse','quality','shipping'].map((name,i)=><article key={name}><div className="process-image"><Image src={`/images/${name}.jpg`} alt={c.stages[i]} fill sizes="(max-width:760px) 50vw, 25vw"/><span>0{i+1}</span></div><h3>{c.stages[i]}</h3><p>{c.stageBodies[i]}</p></article>)}</div></section>
 <section id="social" className="social-section"><div><p className="eyebrow">NEVERSTOP / SOCIAL</p><h2>{c.socialTitle}</h2><p>{c.socialBody}</p></div><div className="social-links">{socialLinks.map(v=><a className="social-account" key={v.name} href={v.href} target="_blank" rel="noopener noreferrer" aria-label={`${v.name}: ${v.handle}`}><span className="social-icon"><SocialIcon name={v.name}/></span><span className="social-platform">{v.name}</span><span className="social-handle">{v.handle}</span></a>)}<span className="social-account social-pending"><span className="social-icon"><SocialIcon name="YouTube"/></span><span className="social-platform">YouTube</span><span className="social-handle">{c.pending}</span></span>{(['B2B','B2C'] as const).map(type=><a className="social-account" key={type} href={zaloChannels[type].url} target="_blank" rel="noopener noreferrer" aria-label={`Zalo · ${zaloChannels[type].title} · ${zaloChannels[type].phone}`}><span className="social-icon"><SocialIcon name="Zalo"/></span><span className="social-platform">Zalo · {type==='B2B'?contactCopy[locale].business:contactCopy[locale].owner}</span><span className="social-handle">{zaloChannels[type].phone.replace(/(\d{4})(\d{3})(\d{3})/,'$1 $2 $3')}</span></a>)}</div></section>
 <section id="contact" className="home-section visit-section"><div><p className="eyebrow">HÀ NỘI / VIETNAM</p><h2>{c.contactTitle}</h2><p>{c.contactBody}</p><a className="button dark" href={maps} target="_blank" rel="noopener noreferrer" aria-label={`${c.directions} · Google Maps`}><BrandIcon name="Google Maps" size={26}/>{c.directions} ↗</a></div><div className="contact-details"><h3>NEVERSTOP <span>FACTORY STORE</span></h3><address>{address}</address></div><ZaloContact locale={locale}/></section>
 <div className="mobile-contact"><a href="#contact"><BrandIcon name="Zalo"/>{contacts[0].audience[locale]} · {c.call} / Zalo</a><a href={contacts[1].zaloHref} target="_blank" rel="noopener noreferrer"><BrandIcon name="Zalo"/>{contacts[1].audience[locale]} · Zalo ↗</a></div>
 </main>;
}
