'use client';
import Link from 'next/link';
import {usePathname} from 'next/navigation';
import {useEffect,useRef,useState,useSyncExternalStore} from 'react';
import {locales,type Locale} from '@/lib/i18n';
import {headerCopy,languageNames,languageFlags} from '@/lib/header-copy';
import {socialLinks} from '@/lib/social-config';
import SocialIcon from './social-icon';
import ZaloVideoIcon from './zalo-video-icon';
import './header.css';
const subscribeHash=(notify:()=>void)=>{window.addEventListener('hashchange',notify);window.addEventListener('popstate',notify);return()=>{window.removeEventListener('hashchange',notify);window.removeEventListener('popstate',notify);};};
export default function SiteHeader({locale}:{locale:Locale}){
 const t=headerCopy[locale],pathname=usePathname();
 const [open,setOpen]=useState(false),[languages,setLanguages]=useState(false);
 const languageRegion=useRef<HTMLDivElement>(null),languageTrigger=useRef<HTMLButtonElement>(null),mobileTrigger=useRef<HTMLButtonElement>(null);
 const hash=useSyncExternalStore(subscribeHash,()=>window.location.hash,()=>'');
 useEffect(()=>{function outside(e:PointerEvent){if(!languageRegion.current?.contains(e.target as Node))setLanguages(false);}function escape(e:KeyboardEvent){if(e.key==='Escape'){if(languages){setLanguages(false);languageTrigger.current?.focus();}if(open){setOpen(false);mobileTrigger.current?.focus();}}}document.addEventListener('pointerdown',outside);document.addEventListener('keydown',escape);return()=>{document.removeEventListener('pointerdown',outside);document.removeEventListener('keydown',escape);};},[languages,open]);
 const nav=[{href:`/${locale}`,label:t.home,key:'home'},{href:`/${locale}/products`,label:t.products,key:'products'},{href:`/${locale}#vehicle-search`,label:t.vehicle,key:'vehicle'},{href:`/${locale}/contact`,label:t.contact,key:'contact'},{href:`/${locale}/orders`,label:t.orders,key:'orders'}];
 function active(key:string){if(key==='vehicle')return pathname===`/${locale}`&&hash==='#vehicle-search';if(key==='home')return pathname===`/${locale}`&&hash!=='#vehicle-search';return pathname===`/${locale}/${key}`||pathname.startsWith(`/${locale}/${key}/`);}
 function switchLanguage(next:Locale){setLanguages(false);setOpen(false);const path=pathname.replace(/^\/(vi|en|zh|ar|es|pt)(?=\/|$)/,'/'+next);window.location.assign(path+window.location.search+window.location.hash);}
 const navigation=nav.map(n=><Link key={n.key} href={n.href} className={active(n.key)?'active':''} aria-current={active(n.key)?'page':undefined} onClick={()=>{setOpen(false);if(n.key==='vehicle')setTimeout(()=>window.dispatchEvent(new Event('hashchange')),0);}}>{n.label}</Link>);
 const socials=<div className="header-socials" aria-label={t.social}><span role="img" aria-label={t.videoPending} title={t.videoPending} data-unavailable="true"><ZaloVideoIcon/></span>{socialLinks.map(s=><a key={s.name} href={s.href} target="_blank" rel="noopener noreferrer" aria-label={s.name} title={s.name}><SocialIcon name={s.name}/></a>)}<span role="img" aria-label={`YouTube · ${t.pending}`} title={`YouTube · ${t.pending}`} data-unavailable="true"><SocialIcon name="YouTube"/></span></div>;
 return <header className="site-header"><a className="sr-only focus:not-sr-only" href="#main">{t.skip}</a><div className="header-inner"><Link href={`/${locale}`} className="header-brand" aria-label="NEVERSTOP Auto Parts" dir="ltr"><strong>NEVERSTOP</strong><small>{t.brandLine}</small></Link><nav className="desktop-nav" aria-label={t.menu}>{navigation}</nav><div className="header-tools"><div className="header-international" ref={languageRegion}><div className="header-languages"><button ref={languageTrigger} type="button" aria-label={t.language} aria-expanded={languages} aria-controls="language-options" className="language-trigger" onClick={()=>setLanguages(v=>!v)}><span className="language-flag" aria-hidden="true">{languageFlags[locale]}</span><span lang={locale} dir={locale==='ar'?'rtl':'ltr'}>{languageNames[locale]}</span><span className="language-chevron" aria-hidden="true">⌄</span></button></div>{socials}{languages&&<div className="language-dropdown" id="language-options" aria-label={t.language}>{locales.map(l=><button key={l} type="button" className={locale===l?'active':''} aria-pressed={locale===l} onClick={()=>switchLanguage(l)}><span className="language-option"><span className="language-flag" aria-hidden="true">{languageFlags[l]}</span><span lang={l} dir={l==='ar'?'rtl':'ltr'}>{languageNames[l]}</span></span>{locale===l&&<span className="language-check" aria-hidden="true">✓</span>}</button>)}</div>}</div><button ref={mobileTrigger} className="mobile-menu-trigger" aria-expanded={open} aria-controls="mobile-nav" onClick={()=>setOpen(v=>!v)}>{t.menu}</button><Link className="header-quote" href={`/${locale}/contact`}>{t.quote}</Link></div></div>{open&&<div className="header-mobile-panel" id="mobile-nav"><nav aria-label={t.menu}>{navigation}</nav><p>{t.language}</p><div className="mobile-languages">{locales.map(l=><button key={l} type="button" aria-pressed={locale===l} className={locale===l?'active':''} onClick={()=>switchLanguage(l)}><span className="language-flag" aria-hidden="true">{languageFlags[l]}</span><span lang={l} dir={l==='ar'?'rtl':'ltr'}>{languageNames[l]}</span>{locale===l&&<span className="language-check" aria-hidden="true">✓</span>}</button>)}</div>{socials}</div>}</header>;
}
