'use client';
import {usePathname} from 'next/navigation';
import {useRef,useState} from 'react';
import {zaloChannels,inquiryText,type CustomerType,type ProductContext} from '@/lib/zalo-config';
import './zalo.css';
function Channel({type,context,compact=false}:{type:CustomerType;context?:ProductContext;compact?:boolean}){const c=zaloChannels[type];const [attempt,setAttempt]=useState(false),[copied,setCopied]=useState(false),[manual,setManual]=useState('');
 function chat(){setAttempt(true);if(context){const value=inquiryText(type,context,location.href);navigator.clipboard?.writeText(value).then(()=>setCopied(true)).catch(()=>setManual(value));if(!navigator.clipboard)setManual(value);}}
 return <article className={compact?"zalo-card zalo-compact":"zalo-card"}><span className="zalo-badge">{type==='B2B'?'B2B · ĐỐI TÁC':'B2C · CHỦ XE'}</span><h3>{c.title}</h3>{!compact&&<p>{c.description}</p>}<strong className="zalo-number">{c.phone.replace(/(\d{4})(\d{3})(\d{3})/,'$1 $2 $3')}</strong><a className="zalo-cta" href={c.url} target="_blank" rel="noopener noreferrer" onClick={chat}>{c.button} ↗</a>{copied&&<p role="status">Thông tin sản phẩm đã được sao chép. Vui lòng dán vào Zalo.</p>}{manual&&<label>Sao chép thông tin để dán vào Zalo<textarea readOnly value={manual} onFocus={e=>e.target.select()}/></label>}
 {(!compact||attempt)&&<><div className="zalo-qr"><img src={c.qr} width="200" height="200" alt={`Zalo QR — ${c.title} — ${c.phone}`}/><p>Quét mã để mở Zalo · {type}</p></div><p>Quét mã bằng Zalo hoặc camera điện thoại để trò chuyện với NEVERSTOP.</p></>}{attempt&&<div role="status"><p>Không mở được Zalo?</p><a href={c.url} target="_blank" rel="noopener noreferrer" onClick={chat}>Thử mở Zalo lại ↗</a><p>Nếu vẫn chưa mở được, hãy quét mã QR ở trên.</p></div>}{!compact&&type==='B2B'&&<a href={`tel:+84${c.phone.replace(/^0/,'')}`}>Gọi điện · {c.phone}</a>}</article>;
}
export default function ZaloContact({context,customerType,compact=false}:{context?:ProductContext;customerType?:CustomerType;compact?:boolean}){return <section className="zalo-contact"><p className="zalo-kicker">LIÊN HỆ QUA ZALO</p><h2>Bạn là khách hàng nào?</h2><p>Vui lòng chọn kênh Zalo phù hợp.</p><div className="zalo-grid">{(customerType?[customerType]:['B2B','B2C'] as CustomerType[]).map(type=><Channel key={type} type={type} context={context} compact={compact}/>)}</div></section>;}
export function ZaloChatButton({context,customerType,label='Hỏi giá qua Zalo',floating=false}:{context?:ProductContext;customerType?:CustomerType;label?:string;floating?:boolean}){const dialog=useRef<HTMLDialogElement>(null);return <><button type="button" className={floating?'zalo-floating':'zalo-cta'} onClick={()=>dialog.current?.showModal()}>{label}</button><dialog aria-label="Chọn kênh tư vấn" className="zalo-dialog" ref={dialog} onClick={e=>{if(e.target===e.currentTarget)dialog.current?.close();}}><button type="button" className="zalo-close" onClick={()=>dialog.current?.close()} aria-label="Đóng">Đóng ×</button><ZaloContact context={context} customerType={customerType} compact/></dialog></>;}

export function GlobalZalo(){const path=usePathname();return path.startsWith("/admin")?null:<ZaloChatButton floating label="Zalo Chat"/>;}
