'use client';
import {contentLocale,localeOf} from '@/lib/i18n';
import {usePathname} from 'next/navigation';
import {useRef,useState} from 'react';
import {zaloChannels,whatsappChannel,contactCopy,inquiryText,overseasInquiry,type CustomerType,type ProductContext} from '@/lib/zalo-config';
import type {Locale} from '@/lib/i18n';
import BrandIcon from './brand-icon';
import './zalo.css';
function useLocale(explicit?:Locale):Locale {const path=usePathname();return explicit||localeOf(path.split('/')[1]);}
function title(type:CustomerType,locale:Locale){return type==='B2B'?contactCopy[contentLocale(locale)].business:contactCopy[contentLocale(locale)].owner;}
function phone(value:string){return value.replace(/(\d{4})(\d{3})(\d{3})/,'$1 $2 $3');}
function Channel({type,context,compact=false,locale,store=false}:{type:CustomerType;context?:ProductContext;compact?:boolean;locale:Locale;store?:boolean}){
 const c=zaloChannels[type],copy=contactCopy[contentLocale(locale)];const [attempt,setAttempt]=useState(false),[copied,setCopied]=useState(false),[manual,setManual]=useState('');
 function chat(){setAttempt(true);if(context){const value=inquiryText(type,context,location.href);navigator.clipboard?.writeText(value).then(()=>setCopied(true)).catch(()=>setManual(value));if(!navigator.clipboard)setManual(value);}}
 return <article className={compact?'zalo-card zalo-compact':'zalo-card'}><span className="zalo-badge">VIETNAM · {type}</span><h3>{title(type,locale)}</h3><p>{c.title}</p><strong className="zalo-number">{phone(c.phone)}</strong><a className="zalo-cta" href={c.url} target="_blank" rel="noopener noreferrer" onClick={chat}><BrandIcon name="Zalo"/>Zalo ↗</a>{copied&&<p role="status">{copy.copied}</p>}{manual&&<label>Copy / Sao chép<textarea readOnly value={manual} onFocus={e=>e.target.select()}/></label>}
 {(!compact||attempt)&&<div className="zalo-qr"><img src={c.qr} width="200" height="200" alt={`Zalo QR — ${title(type,locale)} — ${c.phone}`}/><p>{store?(locale==='zh'?'扫码联系':locale==='vi'?'Quét mã Zalo':'Scan to chat'):<>{copy.qr} · {title(type,locale)}</>}</p></div>}{attempt&&<div role="status"><a href={c.url} target="_blank" rel="noopener noreferrer" onClick={chat}><BrandIcon name="Zalo" size={20}/>{copy.retry} ↗</a></div>}{!compact&&type==='B2B'&&<a href={`tel:+84${c.phone.replace(/^0/,'')}`}>Tel · {phone(c.phone)}</a>}</article>;
}
function Overseas({context,compact=false,locale}:{context?:ProductContext;compact?:boolean;locale:Locale}){const [href,setHref]=useState(whatsappChannel.url);return <article className={compact?'zalo-card zalo-compact overseas-card':'zalo-card overseas-card'}><span className="zalo-badge">INTERNATIONAL · FACTORY</span><h3>{contactCopy[contentLocale(locale)].overseas}</h3><p>Overseas Customers · Direct Factory Contact</p><strong className="zalo-number">+{whatsappChannel.phone.replace(/^(84)(\d{3})(\d{3})(\d{3})$/,'$1 $2 $3 $4')}</strong><a className="zalo-cta whatsapp-cta" href={href} target="_blank" rel="noopener noreferrer" onClick={e=>{if(context){const url=new URL(whatsappChannel.url);url.searchParams.set('text',overseasInquiry(context,location.href));e.currentTarget.href=url.href;setHref(url.href);}}}><BrandIcon name="WhatsApp"/>WhatsApp ↗</a></article>;}
export function HeroContacts({locale}:{locale:Locale}) {const c=contactCopy[contentLocale(locale)];return <div className="hero-contacts">{(['B2B','B2C'] as const).map(type=><a key={type} href={zaloChannels[type].url} target="_blank" rel="noopener noreferrer"><BrandIcon name="Zalo"/><span><strong>{title(type,locale)} · Zalo</strong><small>{zaloChannels[type].title}</small><small className="hero-contact-number" dir="ltr">{phone(zaloChannels[type].phone)}</small></span></a>)}<a href={whatsappChannel.url} target="_blank" rel="noopener noreferrer"><BrandIcon name="WhatsApp"/><span><strong>{c.overseas}</strong><small>Overseas Customers · Direct Factory Contact</small><small className="hero-contact-number" dir="ltr">+{whatsappChannel.phone.replace(/^(84)(\d{3})(\d{3})(\d{3})$/,'$1 $2 $3 $4')}</small></span></a><a className="hero-email" href="mailto:neverstopautoparts06@gmail.com"><svg className="hero-email-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" aria-hidden="true"><rect x="2" y="4" width="20" height="16" rx="2"/><path d="m3 6 9 7 9-7"/></svg><span><strong>{locale==='zh'?'联系邮箱':locale==='vi'?'Email liên hệ':'Contact email'}</strong><small className="hero-contact-number" dir="ltr">neverstopautoparts06@gmail.com</small></span></a></div>;}
export default function ZaloContact({context,customerType,compact=false,locale:explicit,store=false}:{context?:ProductContext;customerType?:CustomerType;compact?:boolean;locale?:Locale;store?:boolean}){const locale=useLocale(explicit),c=contactCopy[contentLocale(locale)];return <section className={store?"zalo-contact store-channels":"zalo-contact"} aria-label={store?c.contact:undefined}>{!store&&<><p className="zalo-kicker">ZALO / WHATSAPP</p><h2>{c.choose}</h2><p>{c.hint}</p></>}<div className={`zalo-grid${customerType?' assigned-channel':''}`}>{(customerType?[customerType]:['B2B','B2C'] as CustomerType[]).map(type=><Channel key={type} type={type} context={context} compact={compact} locale={locale} store={store}/>)}{!customerType&&<Overseas context={context} compact={compact} locale={locale}/>}{store&&!customerType&&<article className="zalo-card store-email-card"><span className="zalo-badge">EMAIL · FACTORY</span><h3>{locale==='zh'?'联系邮箱':locale==='vi'?'Email liên hệ':'Contact email'}</h3><p>{locale==='zh'?'产品咨询 · 品牌定制 · 工厂合作':locale==='vi'?'Tư vấn sản phẩm · Tùy chỉnh thương hiệu':'Product inquiries · Private label'}</p><a className="store-email-address" href="mailto:neverstopautoparts06@gmail.com" dir="ltr">neverstopautoparts06@gmail.com</a><a className="zalo-cta" href="mailto:neverstopautoparts06@gmail.com"><svg width="19" height="19" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" aria-hidden="true"><rect x="2" y="4" width="20" height="16" rx="2"/><path d="m3 6 9 7 9-7"/></svg>{locale==='zh'?'发送邮件':locale==='vi'?'Gửi email':'Send email'} ↗</a></article>}</div></section>;}
export function ZaloChatButton({context,customerType,label,floating=false}:{context?:ProductContext;customerType?:CustomerType;label?:string;floating?:boolean}){const locale=useLocale(),c=contactCopy[contentLocale(locale)],dialog=useRef<HTMLDialogElement>(null);return <><button type="button" className={floating?'zalo-floating':'zalo-cta'} onClick={()=>dialog.current?.showModal()}><BrandIcon name="Zalo"/>{!customerType&&<BrandIcon name="WhatsApp"/>}{label||(floating?c.contact:c.inquire)}</button><dialog aria-label={c.choose} className="zalo-dialog" ref={dialog} onClick={e=>{if(e.target===e.currentTarget)dialog.current?.close();}}><button type="button" className="zalo-close" onClick={()=>dialog.current?.close()} aria-label="Close">×</button><ZaloContact context={context} customerType={customerType} compact locale={locale}/></dialog></>;}
export function GlobalZalo(){const path=usePathname();return path.startsWith('/admin')?null:<ZaloChatButton floating/>;}
